# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 李传云的博客
email: lcy041536@gmail.com
description: "个人博客，记录学习的点点滴滴"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://shaloulcy.github.io" # the base hostname & protocol for your site
twitter_username: licy
github_username:  shaloulcy

# Build settings
markdown: kramdown
